# Use root/example as user/password credentials
version: '3.4'

services:
  pdf-creator:
    build: .
    image: pdf-creator
    restart: always
    ports:
      - 8000:80
    environment:
      - MODULE_NAME=server
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3309:3306
    environment:
      MYSQL_DATABASE: 'jl_pdf_db'
      MYSQL_ROOT_PASSWORD: '12345'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nginx:
    image: nginx
    ports:
      - 70:70
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - pdf-creator