# Use root/example as user/password credentials
version: '3.1'

services:
  pdf-creator:
    build: .
    image: pdf-creator
    restart: always
    ports:
      - 8000:80
    environment:
      - MODULE_NAME=server
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3309:3306
    environment:
      MYSQL_DATABASE: 'jl_pdf_db'
      MYSQL_ROOT_PASSWORD: '12345'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080